91. 如何从一个常规数组中创建记录数组(record array)

In [2]:
import numpy as np
z=np.array([('hello',2.5,3),
           ('world',3.5,2)])
#从(flat)数组列表创建记录数组参数：arrayList：list或tuple
类数组对象的列表（例如，列表，元组和
R=np.core.records.fromarrays(z.T,
                            names='col1,col2,col3',
                            formats='S8,f8,i8')
print(R)

[(b'hello', 2.5, 3) (b'world', 3.5, 2)]


In [4]:
li1=np.array([101,102,103,104])
li2=np.array(['Jitender','Purnima','Ruhi','Varun'])
li3=np.array([21,22,12,35])
gfg=np.core.records.fromarrays([li1,li2,li3],
                              names='Rollno,Name,Age')
print(gfg)

[(101, 'Jitender', 21) (102, 'Purnima', 22) (103, 'Ruhi', 12)
 (104, 'Varun', 35)]


92. 思考一个大向量Z, 用三种不同的方法计算它的立方 

In [11]:
x=np.random.rand(5)
print(x)
A=np.power(x,3)
print(A)



[0.67977838 0.2336745  0.22208682 0.30996378 0.86198932]
[0.31412468 0.01275951 0.01095389 0.02978056 0.64048012]


In [12]:
x=np.random.rand(5)#本函数可以返回一个或一组服从“0~1”均匀分布的随机样本值
print(x)
b=x*x*x
print(b)

[0.64530039 0.48367121 0.41299188 0.91770739 0.94635782]
[0.26871121 0.113149   0.07044084 0.7728811  0.84755155]


In [13]:
x=np.random.rand(5)
print(x)
c=np.einsum('i,i,i->i',x,x,x)
print(c)

[0.46682427 0.97697002 0.50354112 0.53405455 0.81068349]
[0.10173263 0.93248897 0.12767469 0.15231997 0.53278744]


93. 考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？

In [1]:
import numpy as np
a=np.random.randint(0,5,(8,3))#数组的行和列一般都是从零开始
b=np.random.randint(0,5,(2,2))
print(a)
print(b)
c=(a[...,np.newaxis,np.newaxis]==b)
rows=np.where(c.any((3,1)).all(1))[0]
print(rows)


[[4 4 1]
 [3 2 1]
 [3 2 2]
 [2 1 1]
 [4 1 3]
 [0 4 3]
 [1 1 4]
 [3 2 0]]
[[3 3]
 [3 3]]
[1 2 4 5 7]


In [2]:
d=np.arange(0,10)
print(d)
d.shape=(10,1)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [3]:
print(np.arange(0,10)[:,np.newaxis])


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [5]:
a=np.random.randint(0,5,(8,3))
b=np.random.randint(0,5,(2,2))
c=(a[...,np.newaxis,np.newaxis]==b)
print(a)
print(b)
print(c)

[[3 0 1]
 [0 2 1]
 [1 2 3]
 [2 4 4]
 [0 0 2]
 [3 3 3]
 [3 3 0]
 [1 4 3]]
[[3 0]
 [4 3]]
[[[[ True False]
   [False  True]]

  [[False  True]
   [False False]]

  [[False False]
   [False False]]]


 [[[False  True]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[ True False]
   [False  True]]]


 [[[False False]
   [False False]]

  [[False False]
   [ True False]]

  [[False False]
   [ True False]]]


 [[[False  True]
   [False False]]

  [[False  True]
   [False False]]

  [[False False]
   [False False]]]


 [[[ True False]
   [False  True]]

  [[ True False]
   [False  True]]

  [[ True False]
   [False  True]]]


 [[[ True False]
   [False  True]]

  [[ True False]
   [False  True]]

  [[False  True]
   [False False]]]


 [[[False False]
   [False False]]

  [[False False]
   [ True False]]

  [[ True False]
   [False  True]]]]


94. 思考一个10x3的矩阵，如何分解出有不全相同值的行

In [9]:
z=np.random.randint(0,5,(10,3))
print(z)
e=np.all(z[:,1:]==z[:,:-1],axis=1)#二维切片的使用，前面是行，后面是列
u=z[~e]
print(u)
u=z[z.max(axis=1)!=z.min(axis=1),:]# axis=0 代表行 , axis=1 代表列
print(u)

[[4 3 3]
 [0 4 1]
 [3 0 3]
 [2 1 3]
 [2 0 2]
 [0 2 4]
 [2 0 4]
 [4 1 2]
 [0 4 4]
 [0 0 3]]
[[4 3 3]
 [0 4 1]
 [3 0 3]
 [2 1 3]
 [2 0 2]
 [0 2 4]
 [2 0 4]
 [4 1 2]
 [0 4 4]
 [0 0 3]]
[[4 3 3]
 [0 4 1]
 [3 0 3]
 [2 1 3]
 [2 0 2]
 [0 2 4]
 [2 0 4]
 [4 1 2]
 [0 4 4]
 [0 0 3]]


95. 将一个整数向量转换为二进制矩阵（二进制矩阵，除了0就是1）

In [2]:
import numpy as np
i=np.array([0,1,2,3,15,16,32,64,128])
print(i)
#.astype(bool),astype的中文意思，作为布尔类型，也就是true or false
b=((i.reshape(-1,1)&(2**np.arange(8)))!=0).astype(int)#.astype(int)是把布尔类型的转换为为整型数据（0或1）
print(b)
print(b[:,::-1])#行全取完，列倒着取


[  0   1   2   3  15  16  32  64 128]
[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


96. 给定一个二维数组，如何提取出唯一的行?

In [3]:
z=np.random.randint(0,2,(6,3))
print(z)
t=np.ascontiguousarray(z).view(np.dtype((np.void,z.dtype.itemsize*z.shape[1])))
_,idx=np.unique(t,return_index=True)
uz=z[idx]
print(uz)

[[1 1 0]
 [1 0 1]
 [0 0 0]
 [1 0 1]
 [0 1 1]
 [0 1 1]]
[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


97. 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数 

In [4]:
a=np.random.uniform(0,1,10)#numpy.random.uniform(low,high,size) 
print(a)

[0.80835545 0.01884064 0.66227598 0.67037415 0.34390151 0.62765379
 0.42168773 0.53391188 0.84702282 0.08126585]


In [5]:
A = np.random.uniform(0,1,10)
print(A)
B = np.random.uniform(0,1,10)
print(B)
#np.sum(A)
np.einsum('i->',A)#数组A值的总和
#A*B
np.einsum('i,i->i',A,B)#A和B员依次相乘
#np.inner(A,B)
np.einsum('i,i',A,B)#A和B的内积
#np.outer(A,B)
np.einsum('i,j->ij',A,B)#A和B的外积

[0.01721075 0.57989939 0.27376894 0.62487154 0.80045382 0.25397661
 0.59663956 0.07691739 0.9768242  0.36177143]
[0.38808539 0.53633479 0.92839822 0.69056921 0.52966349 0.53397243
 0.19871254 0.62009691 0.1271195  0.70619478]


array([[0.00667924, 0.00923072, 0.01597843, 0.01188521, 0.00911591,
        0.00919007, 0.00341999, 0.01067233, 0.00218782, 0.01215414],
       [0.22505048, 0.31102021, 0.53837756, 0.40046066, 0.30715154,
        0.30965028, 0.11523328, 0.35959382, 0.07371652, 0.40952192],
       [0.10624573, 0.14683181, 0.2541666 , 0.1890564 , 0.14500541,
        0.14618507, 0.05440132, 0.16976327, 0.03480137, 0.1933342 ],
       [0.24250352, 0.33514034, 0.58012962, 0.43151705, 0.33097164,
        0.33366417, 0.12416981, 0.38748091, 0.07943336, 0.44128102],
       [0.31064443, 0.42931123, 0.74313989, 0.55276876, 0.42397117,
        0.42742027, 0.15906021, 0.49635894, 0.10175329, 0.5652763 ],
       [0.09856461, 0.13621649, 0.23579143, 0.17538843, 0.13452214,
        0.13561651, 0.05046834, 0.15749011, 0.03228538, 0.17935696],
       [0.2315471 , 0.31999855, 0.5539191 , 0.41202091, 0.31601819,
        0.31858907, 0.11855976, 0.36997435, 0.07584452, 0.42134374],
       [0.02985052, 0.04125347, 0.0714099

In [7]:
A = np.random.randint(1,10,10)
print(A)
np.einsum('i->',A)#数组A值的总和

[1 3 8 3 9 6 3 1 9 8]


51

In [8]:
A = np.random.randint(1,10,10)
print(A)
B=np.random.randint(1,10,10)
print(B)
np.einsum('i,i->i',A,B)#A和B员依次相乘

[8 1 3 3 4 8 8 7 8 7]
[8 9 6 8 8 8 4 9 8 4]


array([64,  9, 18, 24, 32, 64, 32, 63, 64, 28])

In [9]:
np.einsum('i,i',A,B)#A和B的内积

398

In [10]:
np.einsum('i,j->ij',A,B)#A和B的外积

array([[64, 72, 48, 64, 64, 64, 32, 72, 64, 32],
       [ 8,  9,  6,  8,  8,  8,  4,  9,  8,  4],
       [24, 27, 18, 24, 24, 24, 12, 27, 24, 12],
       [24, 27, 18, 24, 24, 24, 12, 27, 24, 12],
       [32, 36, 24, 32, 32, 32, 16, 36, 32, 16],
       [64, 72, 48, 64, 64, 64, 32, 72, 64, 32],
       [64, 72, 48, 64, 64, 64, 32, 72, 64, 32],
       [56, 63, 42, 56, 56, 56, 28, 63, 56, 28],
       [64, 72, 48, 64, 64, 64, 32, 72, 64, 32],
       [56, 63, 42, 56, 56, 56, 28, 63, 56, 28]])

98. 考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)

In [15]:
phi=np.arange(0,10*np.pi,0.1)
print(phi)
a=1
x=a*phi*np.cos(phi)
y=a*phi*np.sin(phi)
dr=(np.diff(x)**2+np.diff(y)**2)**.5
r=np.zeros_like(x)
r[1:]=np.cumsum(dr)
r_int=np.linspace(0,r.max(),200)
x_int=np.interp(r_int,r,x)
y_int=np.interp(r_int,r,y)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1
 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5
 12.6 12.7 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9
 14.  14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3
 15.4 15.5 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7
 16.8 16.9 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1
 18.2 18.3 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5
 19.6 

In [16]:
phi=np.arange(0,10*np.pi,0.1)
print(phi)
a=1
x=a*phi*np.cos(phi)
y=a*phi*np.sin(phi)
dr=(np.diff(x)**2+np.diff(y)**2)**.5
print(dr)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1
 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5
 12.6 12.7 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9
 14.  14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3
 15.4 15.5 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7
 16.8 16.9 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1
 18.2 18.3 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5
 19.6 