71. 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？

In [2]:
import numpy as np
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72. 如何对一个数组中任意两行做交换?

In [3]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
A = np.arange(25).reshape(5,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [5]:
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


73. 思考描述10个三角形（共享顶点）的一组10个三元组，找到组成所有三角形的唯一线段集

In [6]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(15, 42) (15, 79) (22, 70) (22, 82) (27, 44) (27, 48) (29, 45) (29, 56)
 (39, 46) (39, 48) (42, 79) (44, 48) (45, 56) (46, 48) (47, 48) (47, 60)
 (48, 60) (49, 89) (49, 93) (54, 55) (54, 75) (55, 62) (55, 75) (55, 88)
 (62, 88) (66, 71) (66, 89) (70, 82) (71, 89) (89, 93)]


74. 给定一个二进制的数组C，如何生成一个数组A满足np.bincount(A)==C?

In [7]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)#np.arange()函数按照步长创建一个介于[start, end)前闭后开区间的一维数组
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


75. 如何通过滑动窗口计算一个数组的平均数

In [9]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(Z)
print(moving_average(Z, n=3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


76. 思考以为数组Z，构建一个二维数组，其第一行是(Z[0],Z[1],Z[2])，
然后每一行移动一位，最后一行为 (Z[-3],Z[-2],Z[-1])

In [10]:
from numpy.lib import stride_tricks
 
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


77. 如何对布尔值取反，或改变浮点数的符号(sign)?

In [12]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
print(Z)
 
Z = np.random.uniform(-1.0,1.0,100)
print(Z)
np.negative(Z, out=Z)

[1 1 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0
 1 0 0 1 0 0 1 0 0 1 1 0 1 0 1 1 1 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 0 0 0 0 1
 0 1 0 0 1 0 1 1 1 0 1 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0]
[-0.06940774 -0.00679677 -0.09765696 -0.49508855 -0.78781026  0.41201409
 -0.03291647  0.62178537 -0.92143083 -0.49242381  0.4320162  -0.21735279
  0.52663996  0.50593735 -0.78925251 -0.7688108  -0.37056419 -0.3541196
  0.6811934   0.24980615  0.01529127 -0.00455915 -0.28248048  0.61232168
  0.53227857  0.36660704 -0.26389551 -0.39952796  0.48098742  0.90457916
  0.14946623 -0.31093527  0.47879312 -0.53767172 -0.97080003 -0.63477866
  0.93266422  0.4313462  -0.65536575  0.99190092 -0.51393628  0.45627917
  0.7950913   0.09979199  0.04529323  0.72638342 -0.79438932 -0.61110218
  0.86671814  0.2503037   0.68656564 -0.41243708  0.51389619  0.79570837
  0.67948398  0.54735412  0.15414603 -0.31199179  0.14307199  0.27650661
 -0.80641704  0.4060032   0.66622788  0.8771799   0.90041101 -0.536

array([ 0.06940774,  0.00679677,  0.09765696,  0.49508855,  0.78781026,
       -0.41201409,  0.03291647, -0.62178537,  0.92143083,  0.49242381,
       -0.4320162 ,  0.21735279, -0.52663996, -0.50593735,  0.78925251,
        0.7688108 ,  0.37056419,  0.3541196 , -0.6811934 , -0.24980615,
       -0.01529127,  0.00455915,  0.28248048, -0.61232168, -0.53227857,
       -0.36660704,  0.26389551,  0.39952796, -0.48098742, -0.90457916,
       -0.14946623,  0.31093527, -0.47879312,  0.53767172,  0.97080003,
        0.63477866, -0.93266422, -0.4313462 ,  0.65536575, -0.99190092,
        0.51393628, -0.45627917, -0.7950913 , -0.09979199, -0.04529323,
       -0.72638342,  0.79438932,  0.61110218, -0.86671814, -0.2503037 ,
       -0.68656564,  0.41243708, -0.51389619, -0.79570837, -0.67948398,
       -0.54735412, -0.15414603,  0.31199179, -0.14307199, -0.27650661,
        0.80641704, -0.4060032 , -0.66622788, -0.8771799 , -0.90041101,
        0.5367133 , -0.30942212,  0.15537167,  0.33944945,  0.39

78. 思考两组点集P0和P1去描述一组线(二维)和一个点p,
如何计算点p到每一条线 i (P0[i],P1[i])的距离？

In [14]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
 
P0 = np.random.uniform(-10,10,(10,2))
print(P0)
P1 = np.random.uniform(-10,10,(10,2))
print(P1)
p  = np.random.uniform(-10,10,( 1,2))
print(p)
print(distance(P0, P1, p))

[[-4.58037    -7.30582174]
 [ 5.93293173 -3.1972331 ]
 [ 7.6001313   4.2717365 ]
 [-6.35071108 -5.16698357]
 [-0.45951746  5.98521815]
 [ 9.32945655  7.95241987]
 [ 9.91778554  7.22147642]
 [ 8.30082225 -0.78924889]
 [ 1.88678065  5.71725514]
 [ 8.87894879 -0.31703082]]
[[ 2.32786213 -3.68572555]
 [-3.08818761 -1.40841746]
 [ 4.38606668  5.4301984 ]
 [ 3.48616407 -6.23983146]
 [ 7.1037889  -5.8564841 ]
 [ 6.68251668 -7.74801506]
 [ 1.69279854  2.53743699]
 [ 3.8305476  -3.90900553]
 [ 7.13294751  7.35795987]
 [ 3.26822253  2.04664152]]
[[-2.70724927 -1.88215501]]
[ 3.93460317  0.39059551  9.28436145  3.66049239  6.12914106 10.23426906
  1.66304297  5.40368888  5.8817248   5.94050182]


79. 考虑两组点集P0和P1去描述一组线(二维)和一组点集P，
如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离?

In [15]:
P0 = np.random.uniform(-10, 10, (10,2))#返回包含m行，n列，元素是介于min~max开区间之间随机小
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.81459064 15.96323283  0.28294936 11.17248832 11.54365867  2.01237062
   9.93264962  9.01684297 15.12855953 13.01024776]
 [ 5.48743317 15.43217186  6.60494135  2.17794979  0.626602    2.01644398
   0.63139896  3.19015882  2.95880857  0.87611511]
 [ 4.60474567 11.05827267  2.81115406  6.05468046  9.39212587  5.70367037
   5.32734117  6.3866661  12.20984525 11.01477152]
 [10.15624688  5.64543938  8.61553584  3.95962583 12.04235608 11.64116722
   4.4818302   8.50234404 13.97828132 13.82912197]
 [ 8.22220466  1.82688157  7.77866793  3.33062679  5.69170063 12.78031271
   3.04592432  1.78496697  7.06310197  7.60749082]
 [ 9.64325425  1.83579557  8.9746975   1.90631268  7.69686571 13.51602451
   1.35011546  3.7884735   9.05565059  9.60914814]
 [ 2.7501357  13.07782916  0.82816399  7.05162731  8.70776909  3.60130616
   5.89952189  5.90136892 11.85235899 10.26869011]
 [ 1.23560253  4.55947016  1.32147777  6.42968964  1.52508298  7.6019341
   7.57607534  5.15452844  0.33263664  0.31732473]
 

80. 思考一个任意的数组，编写一个函数，该函数提取一个具有固定形状的子部分，
并以一个给定的元素为中心(在该部分填充值)

In [16]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
 
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
 
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
 
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
 
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 1 4 5 5 2 2 3 0 8]
 [4 7 6 4 8 6 6 3 6 8]
 [3 7 8 0 9 9 1 2 2 4]
 [0 5 9 2 1 6 1 7 8 3]
 [2 7 1 0 8 9 7 5 6 1]
 [0 1 5 5 8 6 3 6 6 4]
 [7 9 8 0 6 6 7 4 2 4]
 [0 3 6 1 4 9 2 7 9 4]
 [7 1 9 0 9 2 3 9 1 4]
 [9 7 4 6 6 5 8 0 1 2]]
[[0 0 0 0 0]
 [0 9 1 4 5]
 [0 4 7 6 4]
 [0 3 7 8 0]
 [0 0 5 9 2]]


<ipython-input-16-8bb237041a2d>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


81. 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],
如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]?

In [18]:
Z=np.arange(1,15,dtype=np.uint32)
R=stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. 计算矩阵的秩 
函数：np.linalg.svd(a,full_matrices=1,compute_uv=1)。
参数：

    a是一个形如(M,N)矩阵

    full_matrices的取值是为0或者1，默认值为1，这时u的大小为(M,M)，v的大小为(N,N) 。否则u的大小为(M,K)，v的大小为(K,N) ，K=min(M,N)。

    compute_uv的取值是为0或者1，默认值为1，表示计算u,s,v。为0的时候只计算s。


In [20]:
Z = np.random.uniform(0,1,(10,10))#10行10列
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


83. 如何找出数组中出现频率最高的值?

In [21]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[8 8 2 7 2 3 0 6 8 3 0 6 4 1 6 3 2 4 8 8 4 7 6 2 3 2 5 1 7 7 6 7 5 3 3 2 4
 8 3 5 0 8 4 8 3 8 8 0 7 1]
8


84. 从一个10x10的矩阵中提取出连续的3x3区块

In [22]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 4 1]
   [1 2 2]
   [3 0 3]]

  [[4 1 4]
   [2 2 4]
   [0 3 3]]

  [[1 4 0]
   [2 4 1]
   [3 3 1]]

  [[4 0 1]
   [4 1 1]
   [3 1 2]]

  [[0 1 4]
   [1 1 1]
   [1 2 0]]

  [[1 4 4]
   [1 1 3]
   [2 0 1]]

  [[4 4 0]
   [1 3 3]
   [0 1 4]]

  [[4 0 1]
   [3 3 0]
   [1 4 3]]]


 [[[1 2 2]
   [3 0 3]
   [1 1 3]]

  [[2 2 4]
   [0 3 3]
   [1 3 1]]

  [[2 4 1]
   [3 3 1]
   [3 1 0]]

  [[4 1 1]
   [3 1 2]
   [1 0 1]]

  [[1 1 1]
   [1 2 0]
   [0 1 0]]

  [[1 1 3]
   [2 0 1]
   [1 0 2]]

  [[1 3 3]
   [0 1 4]
   [0 2 4]]

  [[3 3 0]
   [1 4 3]
   [2 4 0]]]


 [[[3 0 3]
   [1 1 3]
   [2 3 3]]

  [[0 3 3]
   [1 3 1]
   [3 3 0]]

  [[3 3 1]
   [3 1 0]
   [3 0 3]]

  [[3 1 2]
   [1 0 1]
   [0 3 1]]

  [[1 2 0]
   [0 1 0]
   [3 1 1]]

  [[2 0 1]
   [1 0 2]
   [1 1 3]]

  [[0 1 4]
   [0 2 4]
   [1 3 4]]

  [[1 4 3]
   [2 4 0]
   [3 4 0]]]


 [[[1 1 3]
   [2 3 3]
   [0 1 0]]

  [[1 3 1]
   [3 3 0]
   [1 0 2]]

  [[3 1 0]
   [3 0 3]
   [0 2 4]]

  [[1 0 1]
   [0 3 1]
   [2 4 1]]

  [[0 1 0]
   

85.创建一个满足 Z[i,j] == Z[j,i]的二维数组子类

In [23]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9 11  5  8  7]
 [11  9  5  1  5]
 [ 5  5  5 42  8]
 [ 8  1 42  2  7]
 [ 7  5  8  7  6]]


86. 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)
关于参数axes的取值：在多维矩阵相乘的时候，要向axes传入一个数组，它的格式是[ x, y ]，上面的例子当中，x = [ 0 ], y = [ 2 ]，意思是使用a_{i j k}的第0维和b_{l m i}的第2维作为相乘的“轴”。注意这里可以取两个矩阵的任意维度，但是所取的两个维度的长度必须相等，如例子中a_{i j k}和b_{l m i}所取的维度长度都为 i 。当然axes的输入可以不止一个“轴”，我们后面会讲到。


In [25]:
p, n = 10, 20
M = np.ones((p,n,n))#创建10个20行20列矩阵
print(M)
V = np.ones((p,n,1))#创建10个20行一列矩阵
print(V)
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[[1.]
  [