In [2]:
#15. 创建一个2维数组，该数组边界值为1，内部的值为0
import numpy as np
Z=np.ones((10,10))#函数返回给定形状和数据类型的新数组，
#其中元素的值设置为1。此函数与numpy zeros（）函数非常相似。
Z[1:-1,1:-1]=0#从第一行开始到倒数第二行，从第一列开始到倒数第第二列所有数改为0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [12]:
#16.如何用0来填充一个数组的边界
Z=np.ones((10,10))
Z=np.pad(Z,pad_width=1,mode='constant',constant_values=0)#pad()是数据边缘填充函数
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
#17.下面表达式运行的结果是什么
0*np.nan


nan

In [14]:
np.nan==np.nan

False

In [15]:
np.inf>np.nan

False

In [16]:
np.nan-np.nan

nan

In [17]:
0.3==3*0.1

False

In [3]:
#18.创建一个5*5的矩阵，且设置值1,2,3,4在其对角线下面一行
Z=np.diag([1,2,3,4],k=-1) #k=-1保证了偏移
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [4]:
#19.创建一个8*8的国际象棋棋盘矩阵
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
#20.思考一下形状为（6,7，8）的数组的形状，且第100个元素的索引（x，y,z)分别是什么
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [6]:
#21.用tile函数创建一个8*8的棋盘矩阵
Z=np.tile(np.array([[1,0],[0,1]]),(4,4))
print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [7]:
#22.对5*5的随机矩阵进行归一化
Z=np.random.random((5,5))
Zmax,Zmin=Z.max(),Z.min()
Z=(Z-Zmin)/(Zmax-Zmin)
print(Z)

[[0.29729949 0.88363951 0.88912722 0.         0.13072095]
 [0.83122914 0.41524708 0.46721622 0.74348734 0.86355702]
 [0.33362939 0.08687692 0.61195242 0.73497391 0.8525917 ]
 [0.54170295 0.05086203 0.8018936  0.34482398 0.0904852 ]
 [0.3549964  0.57797942 1.         0.5222432  0.50800013]]


In [10]:
#23.创建以dtype来表示颜色
color=np.dtype([("r",np.ubyte,1),
               ("g",np.ubyte,1),
               ("b",np.ubyte,1),
               ("a",np.ubyte,1)
               ])
c=np.array((255,255,255,1),dtype=color)
print(c)
# 参考 https://www.runoob.com/numpy/numpy-dtype.html

(255, 255, 255, 1)


<ipython-input-10-1c8194155464>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r",np.ubyte,1),


In [30]:
#一个5*3的矩阵和一个3*2的矩阵相乘，结果是什么
Z=np.dot(np.zeros((5,3)),np.zeros((3,2)))
print(Z)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [32]:
#给定一个一维数组把它牵引从3到8的元素求相反数
Z=np.arange(11)
Z[(3<=Z)&(Z<8)]*=-1
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


In [1]:
print(sum(range(5),-1))


9


In [2]:
#下面的脚本的结果是什么

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [4]:
from numpy import *
print(sum(range(5),-1))#sum是numpy中的sum函数

10


import numpy 和from NumPy import * 的区别
两种方式都是引入NumPy库中的所有函数，对象，变量等，两者的区别在于调用其中内容时不同
以调用NumPy中的random模块，第一种方式要用numpy.random,第二种方式只用random即可

In [13]:
#关于整形的向量Z下面哪些表达式正确
Z = np.arange(1)
print(Z**Z)                       
print(2 << Z >> 2)                
print(Z <- Z)                      
print(1j*Z)                              
print(Z/1/1)                   
print(Z<Z>Z)

[1]
[0]
[False]
[0.+0.j]
[0.]
[False]


In [10]:
#下面表达式的结果分别是什么
np.array(0)/np.array(0)

<ipython-input-10-553368af9937>:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0)/np.array(0)


nan

In [11]:
np.array(0)//np.array(0)

<ipython-input-11-e72bfd15dca1>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0)//np.array(0)


0

In [12]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [13]:
#如何从零位开始舍入浮点数组
Z=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[-9.  1.  9.  9. -5. -4.  6. -1. -5.  1.]


#如何找出两个数组公共的元素



In [15]:
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 4 5 7]


In [14]:
#如何忽略numpy的警告信息
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0
print(Z)

[inf]


In [20]:
#下面表达式是否为真、
np.sqrt(-1)==np.emath.sqrt(-1)

<ipython-input-20-eff3a5fb17f8>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)


False

In [24]:
#如何获取昨天，今天和明天的日期
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
today=np.datetime64('today','D')
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print(tomorrow)

2021-05-01


In [25]:
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print(yesterday)

2021-04-29


In [27]:
#怎么获得所有与2016年7月的所有日期
Z=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [28]:
#如何计算（（A+B)*(-A/2)(不适用中间变量）
#合理使用out可以提升时空效率
A=np.ones(3)*1
print(A)

[1. 1. 1.]


In [29]:
B=np.ones(3)*1
print(B)

[1. 1. 1.]


In [30]:
C=np.ones(3)
print(C)

[1. 1. 1.]


In [31]:
A=np.ones(3)*1
B=np.ones(3)*1
C=np.ones(3)*1
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [32]:
A=np.ones(3)*1
B=np.ones(3)*1
C=np.ones(3)*1
np.add(A,B,out=B)
np.divide(A,2,out=A)#divide函数与数学中的除法相近
np.negative(A,out=A)
np.multiply(A,B,out=A)#multiply函数（a,b)就是个乘法，如果a,b是两个数组，那么对应元素相乘

array([-1., -1., -1.])

In [33]:
A=np.ones(3)*1
B=np.ones(3)*1
C=np.ones(3)*1
cd=np.add(A,B,out=B)
print(cd)

[2. 2. 2.]


In [36]:
A=np.ones(3)*1
B=np.ones(3)*1
C=np.ones(3)*1
np.divide(A,2,out=A)
np.negative(A,out=A)


array([-0.5, -0.5, -0.5])

In [3]:
import numpy as np
A = np.ones(3) * 1
B = np.ones(3) * 1
C = np.ones(3) * 1
np.multiply(A, B, out=A)#数组和矩阵对应位置相乘，输出与相乘数组/矩阵的大小一致

array([1., 1., 1.])

In [6]:
A = np.ones(3) * 2
B = np.ones(3) * 2
C = np.ones(3) * 1
np.multiply(A, B, out=A)

array([4., 4., 4.])

In [7]:
#用5种不同的方法提取随机数组中的整数部分
Z = np.random.uniform(0, 10, 10)
print (Z - Z % 1)

[6. 9. 3. 9. 5. 2. 9. 8. 0. 3.]


In [8]:
Z = np.random.uniform(0, 10, 10)
print(Z)

[1.2615664  9.97859272 4.94770216 7.75180114 2.4348575  7.36296447
 6.28313703 3.32409056 0.03341442 4.00539459]


In [9]:
print (np.floor(Z))

[1. 9. 4. 7. 2. 7. 6. 3. 0. 4.]


5种不同的方法提取随机数组中的整数部分

In [16]:
Z = np.random.uniform(0, 10, 10)
print (Z - Z % 1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 7. 2. 9. 5. 3. 3. 1. 5. 5.]
[2. 7. 2. 9. 5. 3. 3. 1. 5. 5.]
[2. 7. 2. 9. 5. 3. 3. 1. 5. 5.]
[2 7 2 9 5 3 3 1 5 5]
[2. 7. 2. 9. 5. 3. 3. 1. 5. 5.]


In [12]:
print (np.trunc(Z))

[1. 9. 4. 7. 2. 7. 6. 3. 0. 4.]


In [13]:
#创建一个5x5的矩阵且每一行的值范围为从0到4
Z = np.zeros((5, 5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [14]:
#37.如何用一个生成10个整数的函数来构建数组
def generate():
    for x in range(10):
      yield x
Z = np.fromiter(generate(), dtype=float, count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [15]:
#38.创建一个大小为10的随机向量，并把它排序
Z = np.random.random(10)
Z.sort()
print (Z)

[0.20499552 0.2156313  0.26872924 0.33558322 0.47492183 0.50704833
 0.67694024 0.87734665 0.96935054 0.99136385]


39.创建一个大小为10的向量， 值域为0到1，不包括0和1

In [18]:
Z = np.linspace(0, 1, 12, endpoint=True)[1: -1] # 创建等差数列
print (Z) #endpoint：True则包含stop；False则不包含stop

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [17]:
# 41.对一个小数组进行求和有没有办法比np.sum更快
Z = np.arange(10)
np.add.reduce(Z)

45

In [19]:
#如何判断两随机数组相等
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
print(A,B)

[1 1 0 1 0] [0 0 1 1 0]


In [20]:
equal = np.allclose(A,B)#比较两个array是不是每一元素都相等，默认在1e-05的误差范围内
print(equal)
 

False


In [21]:
equal = np.array_equal(A,B)
print(equal)

False


In [19]:
# 43.把数组变为只读 ####(有点问题)
Z = np.zeros(5)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [23]:
Z = np.zeros(5)
print(Z)

[0. 0. 0. 0. 0.]


In [24]:
Z = np.zeros(5)
Z.flags.writeable = False#创建一个只读数组(read-only)

In [25]:
Z[0] = 1

ValueError: assignment destination is read-only

In [26]:
#44.将一个10x2的笛卡尔坐标矩阵转换为极坐标 
Z = np.random.random((10, 2))
print(Z)

[[0.60798339 0.67836005]
 [0.90102321 0.19021453]
 [0.56093716 0.57540959]
 [0.81239931 0.69113616]
 [0.06876219 0.05392916]
 [0.76282316 0.67660403]
 [0.30634767 0.984052  ]
 [0.01828645 0.57484739]
 [0.06432887 0.57672324]
 [0.84691519 0.02732996]]


In [27]:
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2 + Y**2)#sqrt() 方法返回数字x的平方根。
T = np.arctan2(Y, X)#(1)arctan2的输入不仅仅是正切值,而是要输入两个数 x 1 x1 x1和 x 2 x2 x2,或者是两者的数组,正切值是两者的比值 x 1 x 2 \frac{x1}{x2} x2x1​.
#(2)arctan2的值域是 [ − π , π ] [-\pi, \pi] [−π,π], 因为可以根据 x 1 x1 x1和 x 2 x2 x2来确定点落在哪个象限.

print (R)
print (T)

[0.91094246 0.9208824  0.80358366 1.06661232 0.0873876  1.01965297
 1.03063439 0.57513817 0.58029983 0.84735605]
[0.8400543  0.20805456 0.7981334  0.70492035 0.66508494 0.72557142
 1.26899369 1.53899609 1.45971347 0.03225881]


In [28]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
print(X,Y)

[0.04807606 0.81738334 0.17196369 0.14234464 0.53805633 0.67116122
 0.67118901 0.11135353 0.47058509 0.28149495] [0.51785591 0.43450245 0.90517056 0.40848387 0.66116129 0.25715864
 0.91837548 0.69789322 0.24986203 0.59720067]


In [29]:
# 45.创建一个大小为10的随机向量并且将该向量中最大的值替换为0
Z = np.random.random(10)#浮点数范围 : (0,1)
print(Z)
Z[Z.argmax()] = 0
print (Z)

[0.9634939  0.35386142 0.86918722 0.38879643 0.74361731 0.0206606
 0.9537749  0.98015189 0.23426806 0.15567414]
[0.9634939  0.35386142 0.86918722 0.38879643 0.74361731 0.0206606
 0.9537749  0.         0.23426806 0.15567414]


In [30]:
#46.创建一个结构化数组，其中x和y坐标覆盖[0, 1]x[1, 0]区域
Z = np.zeros((5, 5), [('x', float), ('y', float)])
print(Z)
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))#numpy.meshgrid()——生成网格点坐标矩阵
print (Z)
#linspace函数可以生成元素为50的等间隔数列。而前两个参数分别是数列的开头与结尾。如果写入第三个参数，可以制定数列的元素个数。

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [31]:
# 47.给定两个数组X和Y，构造柯西(Cauchy)矩阵C
#np.subtract.outer
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print (C)
print(np.linalg.det(C)) # 计算行列式

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


In [32]:
#48.打印每个numpy 类型的最小和最大可表示值  dtype:[整数类型，dtype或实例]要获取其有关信息的整数数据类型的种类
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)#numpy.iinfo()函数显示整数类型的机器限制
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [20]:
#49.如何打印数组中所有的值
np.set_printoptions(threshold=np.inf)#控制输出的值的个数，其余以…代替；
#当设置打印显示方式threshold=np.nan，意思是输出数组的时候完全输出，不需要省略号将中间数据省略
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [38]:
#50.如何在数组中找到与给定标量接近的值?
Z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(Z-v)).argmin()#用来检索数组中最小值的位置
print(Z[index])

25


In [39]:
v = np.random.uniform(0, 100)
print(v)

72.64668073480205


In [21]:
#51.创建表示位置(x, y)和颜色(r, g, b, a)的结构化数组
Z = np.zeros(10, [('position', [('x', float, 1), 
                                ('y', float, 1)]),
                  ('color',    [('r', float, 1), 
                                ('g', float, 1), 
                                ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-21-864ede00b712>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [('position', [('x', float, 1),


In [2]:
import numpy as np
Z = np.zeros(10, [('position', [('x', float, 1), 
                                ('y', float, 1)]),
                  ('color',    [('r', float, 1), 
                                ('g', float, 1), 
                                ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-2-baa89f093339>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [('position', [('x', float, 1),


In [3]:
#52.思考形状为(100, 2)的随机向量，求出点与点之间的距离 
Z = np.random.random((100, 2))
X, Y = np.atleast_2d(Z[:, 0], Z[:, 1])#将输入的数组转化为至少两维：
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.20395797 0.35509264 ... 0.39225085 0.50550357 0.08025584]
 [0.20395797 0.         0.50983785 ... 0.51276863 0.70493151 0.27107934]
 [0.35509264 0.50983785 0.         ... 0.63236808 0.30272104 0.2768926 ]
 ...
 [0.39225085 0.51276863 0.63236808 ... 0.         0.57991795 0.41903402]
 [0.50550357 0.70493151 0.30272104 ... 0.57991795 0.         0.43387031]
 [0.08025584 0.27107934 0.2768926  ... 0.41903402 0.43387031 0.        ]]


In [4]:
import scipy.spatial
Z = np.random.random((100,2))
D = scipy.spatial.distance.cdist(Z,Z)#函数用于计算两个输入集合的距离
print(D)

[[0.         0.47748062 0.45862338 ... 0.52486523 0.71140376 0.20965001]
 [0.47748062 0.         0.91337138 ... 0.97480225 1.13594378 0.37434143]
 [0.45862338 0.91337138 0.         ... 0.06772449 0.27067984 0.55394646]
 ...
 [0.52486523 0.97480225 0.06772449 ... 0.         0.20542997 0.61114023]
 [0.71140376 1.13594378 0.27067984 ... 0.20542997 0.         0.76286998]
 [0.20965001 0.37434143 0.55394646 ... 0.61114023 0.76286998 0.        ]]


In [5]:
#53.如何将类型为float(32位)的数组类型转换为integer(32位)
Z = np.arange(10, dtype=np.int32)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
Z = Z.astype(np.float32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#如何读取下面的文件
Z = np.genfromtxt("example.txt", delimiter=",")  
print(Z)
    

In [8]:
Z = np.genfromtxt("example.txt", delimiter=",")  #genfromtxt从文本文件加载数据，并按指定处理缺失值
print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


In [10]:
#55.numpy数组枚举(enumerate)的等价操作
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [11]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
for index, value in np.ndenumerate(Z):#枚举方法
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [13]:
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [14]:
#56.构造一个二维高斯矩阵
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X**2 + Y**2)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / (2.0*sigma**2) ))
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [15]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))#meshgrid生成网格点坐标矩阵
print(X,Y)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


In [16]:
#57.如何在二维数组的随机位置放置p个元素
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
#58.减去矩阵每一行的平均值
X = np.random.rand(5, 10)
 
# 新
Y = X - X.mean(axis=1, keepdims=True)
 
# 旧
Y = X - X.mean(axis=1).reshape(-1, 1)
 
print(Y)

[[ 0.13928076 -0.18054032  0.0365948  -0.39058229  0.52289517  0.20607307
  -0.0160559   0.10432504 -0.15957449 -0.26241583]
 [ 0.13838446 -0.10335709 -0.16547401 -0.27393632  0.44109943  0.12399992
  -0.29434446 -0.47497396  0.33949152  0.26911051]
 [ 0.26412739  0.06928609  0.10117706  0.29179127  0.1382823  -0.32031187
  -0.47776399 -0.02944144 -0.19077156  0.15362476]
 [ 0.29588532  0.21587587  0.23674079  0.02108368  0.25989397 -0.27372138
  -0.51818388 -0.45449112  0.22879504 -0.01187829]
 [ 0.11285942  0.15692449 -0.30850072  0.21183292  0.38298853  0.49285721
  -0.43164306 -0.42309875 -0.45363005  0.25940999]]


In [18]:
X = np.random.rand(5, 10)
print(X)

[[0.92558642 0.83921168 0.42075414 0.7757039  0.79625239 0.81786568
  0.53951782 0.15446728 0.20168794 0.07192352]
 [0.40664538 0.81003994 0.16032304 0.3992538  0.49702435 0.78974321
  0.69203644 0.94523206 0.33991686 0.24271242]
 [0.21738198 0.83623289 0.60118738 0.94649148 0.22543437 0.02353259
  0.00744075 0.74166473 0.37378537 0.29440877]
 [0.47645622 0.00380194 0.3365424  0.92767062 0.89974235 0.83489197
  0.10930764 0.25401459 0.99933615 0.05397607]
 [0.2846553  0.98265929 0.27954537 0.66027541 0.23124255 0.0154147
  0.09003265 0.79762429 0.39813704 0.2848458 ]]


In [19]:
X= X.mean(axis=1, keepdims=True)
print(X)

[[0.55429708]
 [0.52829275]
 [0.42675603]
 [0.48957399]
 [0.40244324]]


In [20]:
X=X.mean(axis=1).reshape(-1, 1)
print(X)

[[0.55429708]
 [0.52829275]
 [0.42675603]
 [0.48957399]
 [0.40244324]]


In [21]:

 
# 新
Y = X - X.mean(axis=1, keepdims=True)
 
# 旧
Y = X - X.mean(axis=1).reshape(-1, 1)
 
print(Y)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [22]:
#59.如何对数组通过第n列进行排序
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[ Z[:,1].argsort() ])

[[3 2 5]
 [0 3 1]
 [9 1 0]]
[[9 1 0]
 [3 2 5]
 [0 3 1]]


In [23]:
Z = np.random.randint(0,10,(3,3))
print(Z)

[[5 6 9]
 [4 3 2]
 [9 8 8]]


In [24]:
print(Z[ Z[:,1].argsort() ])

[[4 3 2]
 [5 6 9]
 [9 8 8]]


In [25]:
#60.如何判断一个给定的二维数组存在空列
Z = np.random.randint(0,3,(3,10))
print(Z)

[[0 1 2 2 2 2 2 0 0 1]
 [1 2 0 0 0 2 0 2 2 1]
 [1 2 0 0 2 0 0 2 2 2]]


In [26]:
print((~Z.any(axis=0)).any())

False


In [27]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [22]:
#61.从数组中找出与给定值最接近的值(49题相似)
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.43679506600874773


In [29]:
Z = np.random.uniform(0,1,10)#从一个均匀分布[low,high)中随机采样,size: 输出样本数目
print(Z)

[0.88665733 0.20589218 0.51914934 0.40558444 0.0607125  0.86762125
 0.45163513 0.7151617  0.54321759 0.22658019]


In [24]:
#62.思考形状为(1, 3)和(3, 1)的两个数组形状，如何使用迭代器计算它们的和
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
print(A,B)

[[0]
 [1]
 [2]] [[0 1 2]]


In [31]:
it = np.nditer([A, B, None])#nditer逐个访问数组元素

In [32]:
for x, y, z in it:
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [33]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [26]:
# 类的定义#.63.创建一个具有name属性的数组类 
class NameArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.info = getattr(obj, 'name', "no name")
        
Z = NameArray(np.arange(10), "range_10")
print(Z.name)

range_10


In [27]:
#64.给定一个向量，如何让在第二个向量索引的每个元素加1
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(Z,I)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [7 7 5 5 1 8 7 8 1 5 2 2 6 1 6 0 2 3 2 2]


In [42]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))#np.bincount输出索引值
print(Z)


[3. 5. 7. 2. 2. 4. 2. 2. 1. 2.]


In [40]:
np.add.at(Z, I, 1)
print(Z)

[3. 5. 3. 5. 7. 5. 5. 7. 5. 5.]


我们可以看到x中最大的数为7，因此bin的数量为8，那么它的索引值为0->7
x=np.array([0,1,1,3,2,1,7])
索引0出现了1次，索引1出现了三次。。。。索引5出现了0次
np.bincount(x）
因此 输出结果为：array（[ 1,3,1,1,0,0,0,1])

In [43]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z = np.bincount(I, minlength=len(Z))
print(Z)

[0 2 2 1 2 1 3 3 3 3]


In [28]:
#65.如何根据索引列表I将向量X的元素累加到数组F
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


66.(dtype = ubyte)的(w, h, 3)图像，计算唯一颜色的值

In [29]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#67.求一个四维数组最后两个轴的数据和

In [30]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[57 31 52 53]
 [64 53 72 53]
 [34 71 49 61]]


In [31]:
# 将最后两个维度压缩为一个
# (适用于不接受轴元组参数的函数)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[57 31 52 53]
 [64 53 72 53]
 [34 71 49 61]]


68.一维向量D，如何使用相同大小的向量S来计算D的子集的均值，其描述子集索引

In [32]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.49136091 0.50548761 0.45228808 0.453006   0.49905262 0.5154102
 0.41673229 0.40243427 0.59863902 0.73087031]


In [33]:
# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.491361
1    0.505488
2    0.452288
3    0.453006
4    0.499053
5    0.515410
6    0.416732
7    0.402434
8    0.598639
9    0.730870
dtype: float64


69.获得点积的对角线

In [34]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
 
# Slow version  
np.diag(np.dot(A, B))
 
# Fast version
np.sum(A * B.T, axis=1)

array([1.75637842, 0.89452713, 0.44555306, 1.99550777, 1.82649199])

70.考虑向量[1,2,3,4,5]，如何建立一个新的向量，在每个值之间交错有3个连续的零

In [35]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]
