1.导入numpy、取名为np,并打印numpy的版本和配置信息

In [1]:
import numpy as np


In [2]:
print (np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']


In [3]:
import numpy as np
print("版本为{0}，配置信息为：{1}".format(np.__version__,np.show_config()))

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
版本为1.19.2，配置信息为：None


2.创建长度为10的零向量

In [4]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3.获取数组所占内存大小

In [5]:
z = np.zeros((10,10))
print(z.itemsize*z.size)   #z.itemsize 对象中每个元素的大小,size是对象中元素个数

800


4.获取numpy add函数的文档说明

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

创建一个长度为10的零向量，并把第五个值赋值为1

In [7]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


创建一个值域为10到49的向量

In [8]:
z = np.arange(10,50)#包前不包后
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


将一个向量反转

In [11]:
z = np.arange(10)
print("原向量为{}".format(z))
z = z[::-1]
print("反转后向量{}".format(z))

原向量为[0 1 2 3 4 5 6 7 8 9]
反转后向量[9 8 7 6 5 4 3 2 1 0]


8.创建一个3x3的矩阵，并且值域为0到8

In [13]:
z = np.arange(9).reshape(3,3)#reshape构成矩阵
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9.从数组[1,2,0,0,4,0]中找出非0元素的位置索引

In [14]:
z = np.array([1,2,0,0,4,0])
nz = np.nonzero(z)  # 返回输入数组中非零元素的索引
print(nz)

(array([0, 1, 4], dtype=int64),)


10.创建一个3x3的单位矩阵

In [15]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11.创建一个3x3x3的随机数组

In [16]:
z = np.random.random((3,3,3))#andom取值是（0.1）
print(z)

[[[0.36145706 0.05615291 0.22836416]
  [0.54239044 0.73717635 0.74547222]
  [0.2135619  0.09757338 0.94201539]]

 [[0.46904263 0.59236332 0.55174188]
  [0.40979214 0.03382371 0.72998961]
  [0.71653768 0.27583504 0.53206955]]

 [[0.58214685 0.62780296 0.99316894]
  [0.23795435 0.29899841 0.63483724]
  [0.29886817 0.00169237 0.25724415]]]


12.创建一个10x10的随机数组，并找出该数组中的最大值与最小值

In [17]:
z = np.random.random((10,10))
zmax,zmin = z.max(),z.min()
print(zmax,zmin)

0.9963591901893526 0.0036883100809593783


13.创建一个长度为30的随机向量，并求它的平均值

In [19]:
z = np.random.random(30)
mean = z.mean()#mean求平均值
print(mean)

0.49673453410522234


14.创建一个2维数组，该数组边界值为1，内部值为0

In [20]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


15.用0填充数组边界

In [21]:
z = np.zeros((10,10))
z[1:-1,1:-1] = 1
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


16. Nan 和 地址比较（区别于数值比较）

In [22]:
#None等于None，但是对于nan，nan并不等于nan
print(0 * np.nan)                       
print(np.nan == np.nan)                  
print(np.inf > np.nan)                   
print(np.nan - np.nan)                  
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


17.创建一个5x5的矩阵，且设置1,2,3,4在其对角线下面的一行

In [23]:
z = np.diag([1, 2, 3, 4], k=-1) # k=-1保证了偏移  k为正数时，向上偏移，负数向下
print (z) 

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


18.创建一个8x8的国际象棋棋盘矩阵

In [24]:
z = np.zeros((8, 8), dtype=int)
z[1::2, ::2] = 1 # 第2，4，6，8行，1，3，5，7列
z[::2, 1::2] = 1 # 第1，3，5，7行，2，4，6，8列
print (z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


19.形状为(6, 7, 8)的数组的形状，且第100个元素的索引(x, y, z)分别是什么？

In [25]:
print (np.unravel_index(100, (6, 7, 8))) #获取一个索引值在一个多维数组中的位置

(1, 5, 4)


20.用tile函数创建一个8x8的棋盘矩阵

In [26]:
z = np.tile(np.array([[1, 0], [0, 1]]), (4, 4))   # Numpy的 tile() 函数，就是将原矩阵横向、纵向地复制。
print (z)  # 与18题比较

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


21.对5x5的矩阵进行归一化处理

In [27]:
z = np.random.random((5, 5))
zmax, zmin = z.max(), z.min()
z = (z-zmin)/(zmax-zmin)
print (z)

[[0.3275672  0.34144056 0.15697632 0.39178831 0.60442241]
 [0.34134478 0.14988572 0.16101104 0.78273704 0.52157491]
 [0.51965743 0.         0.43542057 0.56696867 0.69027551]
 [0.29668352 0.433398   0.02283648 0.6509505  0.06084146]
 [0.07552663 1.         0.11754601 0.20816859 0.481351  ]]


22.创建一个dtype来表示颜色(RGBA)

In [28]:
color = np.dtype([("r", "u1"),
                  ("g", "u1"),
                  ("b", "u1"),
                  ("a", "u1")])
c = np.array((255, 255, 255, 1), dtype=color)
print (c)

(255, 255, 255, 1)


23. 一个5x3的矩阵和一个3x2的矩阵相乘

In [29]:
z = np.dot(np.zeros((5, 3)), np.zeros((3, 2)))
print(z)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


24.给定一个一维数组把它索引从3到8的元素求相反数

In [30]:
z = np.arange(11)
print(z)
z[(3 <= z) & (z< 8)] *= -1
print (z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


26. 下面的脚本的结果是什么

In [31]:
print(sum(range(5),-1)) 

9


In [36]:
from numpy import *                     
print(sum(range(5),-1)) 
# import numpy 和from NumPy import * 的区别 
#两种方式都是引入NumPy库中的所有函数，对象，变量等，两者的区别在于调用其中内容时不同 
#以调用NumPy中的random模块，第一种方式要用numpy.random,第二种方式只用random即可

10


27.关于整形的向量Z下面哪些表达式正确

In [33]:
Z = np.arange(1)
print(Z**Z)                       
print(2 << Z >> 2)                
print(Z <- Z)                      
print(1j*Z)                              
print(Z/1/1)                   
print(Z<Z>Z)

[1]
[0]
[False]
[0.+0.j]
[0.]
[False]


28.表达式的结果

In [34]:
print(np.array(0))
print(np.array(0) / np.array(0))                        
print(np.array(0) // np.array(0))                       
print(np.array([np.nan]).astype(int).astype(float))

0
nan
0
[-2.14748365e+09]


<ipython-input-34-f3d4bf05fab5>:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-34-f3d4bf05fab5>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


29.如何从零位开始舍入浮点数组

In [35]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z)) #向上取整

[ 8.67096068  1.93239042  5.64718945 -8.12641936  5.3846405   5.22562307
  7.92426929 -4.17770517  2.06539472 -2.47348466]
[ 9.  2.  6. -9.  6.  6.  8. -5.  3. -3.]


30.如何找出两个数组公共的元素

In [37]:
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)
print(Z1,Z2)


[7 7 3 5 0 4 3 1 5 9] [4 7 2 2 3 6 0 4 9 4]


In [38]:
print (np.intersect1d(Z1, Z2))

[0 3 4 7 9]
