In [1]:
import numpy as np
np.__version__

'1.19.2'

In [2]:
print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']


In [3]:
z=np.zeros(10)
#创建长度为10的零向量
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#获取数组所占内存大小
z=np.zeros((10,10))
print(z.size*z.itemsize)

800


In [5]:
#怎样用命令行获取NumPy add函数的文档说明
np.info


<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x0000027251D25520>, toplevel='numpy')>

In [6]:
#创建一个长度为10的零向量，并把第五个值赋值为1
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#创建一个值域为10到49的向量
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#将一个向量进行反转（第一个元素为最后一个元素
z=np.arange(50)
z=z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [9]:
#创建一个3*3的矩阵，值域为0到8
z=np.arange(9)*reshape(3,3)
print(z)

NameError: name 'reshape' is not defined

In [10]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
#从数组[1,2,0,0,4,]中找出非0的位置索引
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)
